AllCops:
  Exclude:
    - vendor/**/*
  NewCops: enable
  SuggestExtensions:
    rubocop-rake: false

Layout/LineLength:
  Max: 180

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Metrics/MethodLength:
  Max: 30

Metrics/BlockLength:
  Exclude: &fastlane
    - fastlane/Fastfile
    - fastlane/lanes/*.rb

Style/HashSyntax:
  EnforcedShorthandSyntax: never
