# frozen_string_literal: true

default_platform(:android)
fastlane_require 'dotenv'

UI.user_error!('Please run fastlane via `bundle exec`') unless FastlaneCore::Helper.bundler?

USER_ENV_FILE_PATH = File.join(Dir.home, '.simplenoteandroid-env.default')
PROTOTYPE_BUILD_DOMAIN = 'https://cdn.a8c-ci.services'

before_all do
  # TODO: Use EnvManager — https://github.com/wordpress-mobile/release-toolkit/pull/578
  UI.user_error!("#{USER_ENV_FILE_PATH} not found: Please copy env.example to #{USER_ENV_FILE_PATH} and fill in the values") unless is_ci || File.file?(USER_ENV_FILE_PATH)
  Dotenv.load(USER_ENV_FILE_PATH)
end

PROJECT_ROOT_FOLDER = File.dirname(File.expand_path(__dir__))

ORGANIZATION = 'automattic'
REPO_NAME = 'simplenote-android'
GITHUB_REPO = "#{ORGANIZATION}/#{REPO_NAME}".freeze
DEFAULT_BRANCH = 'trunk'
BUILDKITE_ORGANIZATION = ORGANIZATION
BUILDKITE_PIPELINE = REPO_NAME
APP_PACKAGE_NAME = 'com.automattic.simplenote'

APP_SOURCES_FOLDER = File.join(PROJECT_ROOT_FOLDER, 'Simplenote')
METADATA_FOLDER = File.join(APP_SOURCES_FOLDER, 'metadata')
BUILD_FOLDER = File.join(APP_SOURCES_FOLDER, 'build')
RES_FOLDER = File.join(APP_SOURCES_FOLDER, 'src', 'main', 'res')
MAIN_STRINGS_PATH = File.join(RES_FOLDER, 'values', 'strings.xml')
UPDATE_STRINGS_PATH = File.join(PROJECT_ROOT_FOLDER, 'fastlane', 'resources', 'values')

GLOTPRESS_BASE_URL = 'https://translate.wordpress.com/projects'
# URL of the GlotPress project containing the app's strings
#
# Notice the trailing / is required.
# Without it, GlotPress will redirect to the version with /
GLOTPRESS_APP_STRINGS_PROJECT_URL = "#{GLOTPRESS_BASE_URL}/simplenote/android/".freeze
# URL of the GlotPress project containing the Play Store metadata (title, keywords, release notes, …)
GLOTPRESS_STORE_METADATA_PROJECT_URL = "#{GLOTPRESS_APP_STRINGS_PROJECT_URL}release-notes/".freeze

STORE_METADATA_SOURCE_FOLDER = File.join(PROJECT_ROOT_FOLDER, 'fastlane', 'metadata', 'android')
STORE_METADATA_SOURCE_DEFAULT_LOCALE = 'en-US'
STORE_METADATA_SOURCE_DEFAULT_FOLDER = File.join(STORE_METADATA_SOURCE_FOLDER, STORE_METADATA_SOURCE_DEFAULT_LOCALE)
RELEASE_NOTES_PATH = File.join(STORE_METADATA_SOURCE_DEFAULT_FOLDER, 'changelogs', 'default.txt')
RELEASE_NOTES_SOURCE_PATH = File.join(PROJECT_ROOT_FOLDER, 'RELEASE-NOTES.txt')

UPLOAD_TO_PLAY_STORE_JSON_KEY = File.join(Dir.home, '.configure', 'simplenote-android', 'secrets', 'google-upload-credentials.json')

GRADLE_APK_OUTPUT_PATH = File.join(BUILD_FOLDER, 'outputs', 'apk', 'release', 'Simplenote-release.apk')

VERSION_PROPERTIES_PATH = File.join(PROJECT_ROOT_FOLDER, 'version.properties')

VERSION_CALCULATOR = Fastlane::Wpmreleasetoolkit::Versioning::SemanticVersionCalculator.new
VERSION_FORMATTER = Fastlane::Wpmreleasetoolkit::Versioning::RCNotationVersionFormatter.new
BUILD_CODE_FORMATTER = Fastlane::Wpmreleasetoolkit::Versioning::SimpleBuildCodeFormatter.new
BUILD_CODE_CALCULATOR = Fastlane::Wpmreleasetoolkit::Versioning::SimpleBuildCodeCalculator.new
VERSION_FILE = Fastlane::Wpmreleasetoolkit::Versioning::AndroidVersionFile.new(version_properties_path: VERSION_PROPERTIES_PATH)

# Important: These need to be imported after all the constants have been defined because they access them.
# A bit of a leaky abstraction but makes for lanes that are easier to write...
import 'lanes/build.rb'
import 'lanes/localization.rb'
import 'lanes/release.rb'
# This helper is only used in the release lanes but it needs to be imported here in order to access Fastlane-specific API and our methods like release_version_current
import 'lib/release_helpers.rb'

platform :android do
  ENV['PROJECT_ROOT_FOLDER'] = "#{File.dirname(File.expand_path(__dir__))}/"
  ENV['PROJECT_NAME'] = 'Simplenote'
  ENV['validate_translations'] = 'buildRelease'
  ENV['FL_RELEASE_TOOLKIT_DEFAULT_BRANCH'] = 'trunk'

  desc 'Creates a new hotfix branch from the given tag'
  lane :new_hotfix_release do |version_name:, version_code:, skip_confirm: false|
    ensure_git_status_clean

    new_version = version_name
    version_code_new = version_code

    # Validate that this is a hotfix version (must have a patch component > 0)
    parsed_version = VERSION_FORMATTER.parse(new_version)
    UI.user_error!("Invalid hotfix version '#{new_version}'. Must include a patch number.") unless parsed_version.patch.to_i.positive?
    previous_version = VERSION_FORMATTER.release_version(
      VERSION_CALCULATOR.previous_patch_version(version: parsed_version)
    )
    previous_release_branch = release_branch_name(release_version: previous_version)

    UI.user_error!("Version '#{new_version}' already exists on the remote! Abort!") if git_tag_exists(tag: new_version, remote: true)

    # Determine the base for the hotfix branch: either a tag or a release branch
    base_ref_for_hotfix = if git_tag_exists(tag: previous_version, remote: true)
                            previous_version
                          elsif Fastlane::Helper::GitHelper.branch_exists_on_remote?(branch_name: previous_release_branch)
                            UI.message("ℹ️  Tag '#{previous_version}' not found on the remote. Using release branch '#{previous_release_branch}' as the base for hotfix instead.")
                            previous_release_branch
                          else
                            UI.user_error!("Neither tag '#{previous_version}' nor branch '#{previous_release_branch}' exists on the remote! A hotfix branch cannot be created.")
                          end

    message = <<~MESSAGE
      Hotfix release:
      - Current release version: #{release_version_current}
      - New hotfix version: #{new_version}

      - Current build code: #{build_code_current}
      - New build code: #{version_code_new}

      Branching from #{base_ref_for_hotfix}
    MESSAGE
    UI.important(message)

    UI.user_error!("Terminating as requested. Don't forget to run the remainder of this automation manually.") unless skip_confirm || UI.confirm('Do you want to continue?')

    # Fetch the base ref to ensure it's available locally
    sh('git', 'fetch', 'origin', base_ref_for_hotfix)

    hotfix_branch = release_branch_name(release_version: new_version)
    ensure_branch_does_not_exist!(hotfix_branch)

    UI.message("Creating hotfix branch from '#{base_ref_for_hotfix}'...")
    Fastlane::Helper::GitHelper.create_branch(hotfix_branch, from: base_ref_for_hotfix)
    UI.success("Done! New hotfix branch is: '#{git_branch}'")

    UI.message('Bumping hotfix version and build code...')
    VERSION_FILE.write_version(
      version_name: new_version,
      version_code: version_code_new
    )
    commit_version_bump
    # Print computed version and build to let user double-check outcome in logs
    UI.success("Done! New release version: '#{release_version_current}'. New build code: '#{build_code_current}'.")

    UI.important('Pushing new hotfix branch to remote...')
    push_to_git_remote(tags: false)

    # TODO: Switch to working branch and open back-merge PR
  end

  desc 'Finalizes a hotfix release by tagging the build'
  lane :finalize_hotfix_release do |skip_confirm: false|
    ensure_git_status_clean
    ensure_git_branch_is_release_branch!

    hotfix_version = release_version_current

    UI.important("Triggering hotfix build for version: #{hotfix_version}...")
    UI.user_error!("Terminating as requested. Don't forget to run the remainder of this automation manually.") unless skip_confirm || UI.confirm('Do you want to continue?')

    trigger_release_build(branch_to_build: release_branch_name)
  end

  desc 'Build a Prototype Build and make it available for download'
  lane :build_and_upload_prototype_build do
    UI.user_error!("'BUILDKITE_ARTIFACTS_S3_BUCKET' must be defined as an environment variable.") unless ENV['BUILDKITE_ARTIFACTS_S3_BUCKET']

    prototype_build_type = 'Debug'

    gradle(
      task: 'assemble',
      build_type: prototype_build_type
    )

    filename = "simplenote-android-prototype-build-#{generate_prototype_build_number}.apk"

    upload_path = upload_to_s3(
      bucket: 'a8c-apps-public-artifacts',
      key: filename,
      file: lane_context[SharedValues::GRADLE_APK_OUTPUT_PATH]
    )

    return if ENV['BUILDKITE_PULL_REQUEST'].nil?

    install_url = "#{PROTOTYPE_BUILD_DOMAIN}/#{upload_path}"

    unless ENV['BUILDKITE_PULL_REQUEST'].nil?
      comment_body = prototype_build_details_comment(
        app_display_name: 'Simplenote Android',
        download_url: install_url,
        metadata: {
          'Build Type': prototype_build_type
        }
      )

      comment_on_pr(
        project: GITHUB_REPO,
        pr_number: Integer(ENV.fetch('BUILDKITE_PULL_REQUEST', nil)),
        reuse_identifier: 'simplenote-prototype-build-link',
        body: comment_body
      )
    end

    if ENV['BUILDKITE']
      message = "Simplenote Android Prototype Build: [#{filename}](#{install_url})"
      sh('buildkite-agent', 'annotate', message, '--style', 'info', '--context', 'prototype-build')
    end
  end

  desc 'Take screenshots in the app'
  lane :take_screenshots do
    package = "#{APP_PACKAGE_NAME}.debug"

    # Reset the app in the emulator, just to avoid possible state related
    # issues
    begin
      adb(command: "shell pm clear #{package}")
    rescue StandardError
      UI.message('Failed to reset app data on emulator. This can happen when the app is not installed yet.')
    end

    # We use the screenshots build type for the app APK, which allows us to not
    # set the special permissions in the debug build type so that it doesn't
    # deviate from the release one. For the test APK though, we still use the
    # debug build type, as it's the only testable one, and there's no need to
    # make a dedicated one for the screenshots.
    gradle(task: 'assemble', build_type: 'Screenshots')
    gradle(task: 'assemble', build_type: 'DebugAndroidTest')

    capture_android_screenshots(
      locales: ['en-US'],
      output_directory: screenshots_directory,
      clear_previous_screenshots: false,
      app_package_name: package,
      app_apk_path: File.join(BUILD_FOLDER, 'outputs', 'apk', 'screenshots', 'Simplenote-screenshots.apk'),
      tests_apk_path: File.join(BUILD_FOLDER, 'outputs', 'apk', 'androidTest', 'debug', 'Simplenote-debug-androidTest.apk'),
      # Because the screenshot tests are together with other UI tests, we need
      # to specify to run only them and not all of the others.
      use_tests_in_classes: "#{APP_PACKAGE_NAME}.screenshots.ScreenshotTest",
      use_timestamp_suffix: false,
      # Need to use this in order to get access to the screenshots on the
      # emulator. Also note that you might need to run on a Google API
      # emulator, that is one without the Play Store. See
      # https://github.com/fastlane/fastlane/issues/15788#issuecomment-583778278
      use_adb_root: true
    )
  end

  def screenshots_directory
    File.join(Dir.pwd, 'screenshots')
  end

  private_lane :update_strings_for_translation_automation do
    sh("cd .. && mkdir -p #{UPDATE_STRINGS_PATH} && cp #{MAIN_STRINGS_PATH} #{UPDATE_STRINGS_PATH}")
    strings_path = File.join(UPDATE_STRINGS_PATH, 'strings.xml')
    git_commit(
      path: strings_path,
      message: 'Update strings file for translation automation',
      allow_nothing_to_commit: true
    )
  end

  # Mimics the subset of ActiveSupport's `String#parameterize` we rely on.
  # release-toolkit dropped its `activesupport` runtime dependency in v14.3.1,
  # so `String#parameterize` is no longer available here.
  def parameterize(string)
    string.downcase.gsub(/[^a-z0-9\-_]+/, '-').squeeze('-').gsub(/\A-|-\z/, '')
  end

  # This function is Buildkite-specific
  def generate_prototype_build_number
    if ENV['BUILDKITE']
      commit = ENV.fetch('BUILDKITE_COMMIT', nil)[0, 7]
      branch = parameterize(ENV['BUILDKITE_BRANCH'])
      pr_num = ENV.fetch('BUILDKITE_PULL_REQUEST', nil)

      pr_num == 'false' ? "#{branch}-#{commit}" : "pr#{pr_num}-#{commit}-#{ENV.fetch('BUILDKITE_JOB_ID', nil)}"
    else
      repo = Git.open(PROJECT_ROOT_FOLDER)
      commit = parameterize(repo.current_branch)
      branch = repo.revparse('HEAD')[0, 7]

      "#{branch}-#{commit}"
    end
  end
end

def release_version_current
  current_version = VERSION_FORMATTER.parse(VERSION_FILE.read_version_name)
  VERSION_FORMATTER.release_version(current_version)
end

def release_version_next
  current_version = VERSION_FORMATTER.parse(VERSION_FILE.read_version_name)
  release_version_next = VERSION_CALCULATOR.next_release_version(version: current_version)
  VERSION_FORMATTER.release_version(release_version_next)
end

# Returns the initial beta version for a code freeze (e.g., "1.2-rc-1" for release version "1.2")
# Increments the build number from 0 to 1 to create the first release candidate
#
def release_version_for_code_freeze(version_name: nil)
  # Use provided version or read the current version from version.properties
  version_name ||= VERSION_FILE.read_version_name
  # Parse the version string (e.g., "1.2") into an AppVersion object
  version = VERSION_FORMATTER.parse(version_name)
  # Increment the build number to 1 to get the first beta version
  beta_version_first = VERSION_CALCULATOR.next_build_number(version: version)
  # Format as beta version (e.g., "1.2-rc-1")
  VERSION_FORMATTER.beta_version(beta_version_first)
end

def release_version_next_beta
  current_version = VERSION_FORMATTER.parse(VERSION_FILE.read_version_name)
  beta_version_next = VERSION_CALCULATOR.next_build_number(version: current_version)
  VERSION_FORMATTER.beta_version(beta_version_next)
end

def build_code_current
  build_code_current = VERSION_FILE.read_version_code
  BUILD_CODE_FORMATTER.build_code(build_code: build_code_current)
end

def build_code_next
  build_code_current = VERSION_FILE.read_version_code
  build_code_next = BUILD_CODE_CALCULATOR.next_build_code(build_code: build_code_current)
  BUILD_CODE_FORMATTER.build_code(build_code: build_code_next)
end

def commit_version_bump
  git_commit(
    path: VERSION_PROPERTIES_PATH,
    message: 'Bump version name and build code',
    allow_nothing_to_commit: false
  )
end

def release_branch_name(release_version: release_version_current)
  "#{RELEASE_BRANCH_ROOT}#{release_version}"
end

def ensure_git_branch_is_release_branch!
  # Verify that the current branch is a release branch.
  # Notice that `ensure_git_branch` expects a RegEx parameter.
  # Also, ensure_git_branch will fail the lane if the branch doesn't match, hence the ! in the method name.
  ensure_git_branch(branch: "^#{RELEASE_BRANCH_ROOT}")
end

RELEASE_BRANCH_ROOT = 'release/'

def create_release_backmerge_pr(version_to_merge:, next_version:)
  create_release_backmerge_pull_request(
    repository: GITHUB_REPO,
    source_branch: release_branch_name(release_version: version_to_merge),
    labels: ['Releases'],
    milestone_title: next_version
  )
rescue StandardError => e
  error_message = <<-MESSAGE
    Error creating backmerge pull request: #{e.message}
    If this is not the first time you are running the release task, the backmerge PR for the version `#{version_to_merge}` might have already been previously created.
    Please close any previous backmerge PR for `#{version_to_merge}`, delete the previous merge branch, then run the release task again.
  MESSAGE

  buildkite_annotate(style: 'error', context: 'error-creating-backmerge', message: error_message) if is_ci

  UI.user_error!(error_message)
end

def report_milestone_error(error_title:)
  error_message = <<-MESSAGE
    #{error_title}
    - If this is not the first time you are running the release task (e.g. retrying because it failed on first attempt), the milestone might have already been closed and this error is expected.
    - Otherwise, please investigate the error.
  MESSAGE

  UI.error(error_message)

  buildkite_annotate(style: 'warning', context: 'error-with-milestone', message: error_message) if is_ci
end
